/**
 * Shared share-card image (spec §11).
 *
 * Next merges `metadata` shallowly: a page that declares its own `openGraph`
 * replaces the parent's whole object, images included. So every page that sets
 * `openGraph` must spread these in rather than relying on app/layout.tsx.
 *
 * The file is generated by scripts/generate-og-image.mjs from the brand logo —
 * edit the script, not public/og.png. Paths stay relative; `metadataBase` in
 * app/layout.tsx resolves them to absolute URLs, which every unfurler requires.
 */
const OG_IMAGE = {
  url: "/og.png",
  width: 1200,
  height: 630,
  alt: "Paelon Memorial Hospital",
  type: "image/png",
};

/** Spread into any page's `openGraph`. */
export const OG_IMAGES = [OG_IMAGE];

/** Spread into any page's `twitter`. */
export const TWITTER_IMAGES = [OG_IMAGE.url];
